insert into foglio values('Gecko','Firefox 1.0','Win 98+ / OSX.2+','1.7','A')
insert into foglio values('Gecko','Firefox 1.5','Win 98+ / OSX.2+','1.8','A')
insert into foglio values('Gecko','Firefox 2.0','Win 98+ / OSX.2+','1.8','A')
insert into foglio values('Gecko','Firefox 3.0','Win 2k+ / OSX.3+','1.9','A')
insert into foglio values('Gecko','Camino 1.0','OSX.2+','1.8','A')
insert into foglio values('Gecko','Camino 1.5','OSX.3+','1.8','A')
insert into foglio values('Gecko','Netscape 7.2','Win 95+ / Mac OS 8.6-9.2','1.7','A')
insert into foglio values('Gecko','Netscape Browser 8','Win 98SE+','1.7','A')
insert into foglio values('Gecko','Netscape Navigator 9','Win 98+ / OSX.2+','1.8','A')
insert into foglio values('Gecko','Mozilla 1.0','Win 95+ / OSX.1+',null,'A')
insert into foglio values('Gecko','Mozilla 1.1','Win 95+ / OSX.1+','1.1','A')
insert into foglio values('Gecko','Mozilla 1.2','Win 95+ / OSX.1+','1.2','A')
insert into foglio values('Gecko','Mozilla 1.3','Win 95+ / OSX.1+','1.3','A')
insert into foglio values('Gecko','Mozilla 1.4','Win 95+ / OSX.1+','1.4','A')
insert into foglio values('Gecko','Mozilla 1.5','Win 95+ / OSX.1+','1.5','A')
insert into foglio values('Gecko','Mozilla 1.6','Win 95+ / OSX.1+','1.6','A')
insert into foglio values('Gecko','Mozilla 1.7','Win 98+ / OSX.1+','1.7','A')
insert into foglio values('Gecko','Mozilla 1.8','Win 98+ / OSX.1+','1.8','A')
insert into foglio values('Gecko','Seamonkey 1.1','Win 98+ / OSX.2+','1.8','A')
insert into foglio values('Gecko','Epiphany 2.20','Gnome','1.8','A')
insert into foglio values('KHTML','Konqureror 3.1','KDE 3.1','3.1','C')
insert into foglio values('KHTML','Konqureror 3.3','KDE 3.3','3.3','A')
insert into foglio values('KHTML','Konqureror 3.5','KDE 3.5','3.5','A')
insert into foglio values('Misc','NetFront 3.1','Embedded devices','-','C')
insert into foglio values('Misc','NetFront 3.4','Embedded devices','-','A')
insert into foglio values('Misc','Dillo 0.8','Embedded devices','-','X')
insert into foglio values('Misc','Links','Text only','-','X')
insert into foglio values('Misc','Lynx','Text only','-','X')
insert into foglio values('Misc','IE Mobile','Windows Mobile 6','-','C')
insert into foglio values('Misc','PSP browser','PSP','-','C')
insert into foglio values('Other browsers','All others','-','-','U')
insert into foglio values('Presto','Opera 7.0','Win 95+ / OSX.1+','-','A')
insert into foglio values('Presto','Opera 7.5','Win 95+ / OSX.2+','-','A')
insert into foglio values('Presto','Opera 8.0','Win 95+ / OSX.2+','-','A')
insert into foglio values('Presto','Opera 8.5','Win 95+ / OSX.2+','-','A')
insert into foglio values('Presto','Opera 9.0','Win 95+ / OSX.3+','-','A')
insert into foglio values('Presto','Opera 9.2','Win 88+ / OSX.3+','-','A')
insert into foglio values('Presto','Opera 9.5','Win 88+ / OSX.3+','-','A')
insert into foglio values('Presto','Opera for Wii','Wii','-','A')
insert into foglio values('Presto','Nokia N800','N800','-','A')
insert into foglio values('Presto','Nintendo DS browser','Nintendo DS','8.5','C/A1')
insert into foglio values('Tasman','Internet Explorer 4.5','Mac OS 8-9','-','X')
insert into foglio values('Tasman','Internet Explorer 5.1','Mac OS 7.6-9',null,'C')
insert into foglio values('Tasman','Internet Explorer 5.2','Mac OS 8-X',null,'C')
insert into foglio values('Trident','Internet Explorer 4.0','Win 95+',null,'X')
insert into foglio values('Trident','Internet Explorer 5.0','Win 95+',null,'C')
insert into foglio values('Trident','Internet Explorer 5.5','Win 95+','5.5','A')
insert into foglio values('Trident','Internet Explorer 6','Win 98+',null,'A')
insert into foglio values('Trident','Internet Explorer 7','Win XP SP2+',null,'A')
insert into foglio values('Trident','AOL browser (AOL desktop)','Win XP',null,'A')
insert into foglio values('Webkit','Safari 1.2','OSX.3','125.5','A')
insert into foglio values('Webkit','Safari 1.3','OSX.3','312.8','A')
insert into foglio values('Webkit','Safari 2.0','OSX.4+','419.3','A')
insert into foglio values('Webkit','Safari 3.0','OSX.4+','522.1','A')
insert into foglio values('Webkit','OmniWeb 5.5','OSX.4+',null,'A')
insert into foglio values('Webkit','iPod Touch / iPhone','iPod','420.1','A')
insert into foglio values('Webkit','S60','S60',null,'A')